// active scene
export const SCENE_TOGGLE_POWER = "SCENE_TOGGLE_POWER";
export const SET_ACTIVE_SCENE = "SET_ACTIVE_SCENE";
export const TOGGLE_STRUCTURE_ACTIVE = "TOGGLE_STRUCTURE_ACTIVE";
export const SET_EMPTY_ACTIVE_SCENE = "SET_EMPTY_ACTIVE_SCENE";
export const SET_GRID_SIZE = "SET_GRID_SIZE";

// active structure
export const SET_ACTIVE_STRUCTURE = "SET_ACTIVE_STRUCTURE";

// activeTile
export const SET_ACTIVE_TILE = "SET_ACTIVE_TILE";

// ui
export const RESIZE_PANE = "RESIZE_PANE";
export const OPEN_SYSTEM_VIEWER_MODAL = "OPEN_SYSTEM_VIEWER_MODAL";
export const CLOSE_SYSTEM_VIEWER_MODAL = "CLOSE_SYSTEM_VIEWER_MODAL";

// editor
export const TOGGLE_EDITOR = "TOGGLE_EDITOR";
export const EDITOR_ON = "EDITOR_ON";
export const EDITOR_OFF = "EDITOR_OFF";
